FROM node:16.3.0-slim
# This Dockerfile adds a non-root user with sudo access. Use the "remoteUser"
# property in devcontainer.json to use it. On Linux, the container user's GID/UIDs
# will be updated to match your local UID/GID (when using the dockerFile property).
# See https://aka.ms/vscode-remote/containers/non-root-user for details.
ARG USERNAME=node
ENV USERNAME ${USERNAME}

ARG USER_UID=1000
ARG USER_GID=${USER_UID}

USER root
# [Optional] Uncomment this section to install additional OS packages.
RUN apt-get update \
  && export DEBIAN_FRONTEND=noninteractive && apt-get -y install --no-install-recommends git sudo ca-certificates python3 gcc make pkg-config libx11-dev libxi-dev libxext-dev g++ mesa-common-dev  \
  && adduser $USERNAME sudo \
  && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
  && chmod 0440 /etc/sudoers.d/$USERNAME \
  && ln -s /usr/bin/python3 /usr/bin/python

USER ${USERNAME}